### ISSUE TITLE
Add a detail pane to GTK frontend

### ISSUE THREAD

**Issue by miek** [greatscottgadgets/packetry#10]
This would show more detail about the currently selected `Item`, similar to the behaviour in ViewSB or Wireshark

**Comment by mossmann** [comment]
I was originally thinking that the detail pane would be placed below the traffic pane (like in Wireshark), but it just occurred to me that it could go in the same place as the device pane, perhaps with tabs to select device or detail or potentially other future options.

**Comment by martinling** [comment]
I'm not so keen on that idea because I think for the detail pane we're going to want plenty of width, particularly if we're showing a conventional hexdump view with three columns (offset, hex, ASCII).

I've been thinking of it as being below a draggable separator bar that runs right across the window, beneath both the traffic and the device panes.
