### ISSUE TITLE
Analyzer gateware is older (v0) than supported by this version of Packetry (v1)

### ISSUE THREAD

**Issue by salcho** [greatscottgadgets/packetry#114]
I just received my Cynthion and would like to test the setup described in [these docs](https://cynthion.readthedocs.io/en/latest/getting_started_packetry.html#connect-hardware). I've reproduced the setup and can see my target host correctly talking to the target device.

I've built cynthion from git and `pip install`'d it, which also installs amaranth. I've got versions cynthion-0.0.0.post102+git.11184b3c and amaranth-0.4.1.

In parallel, I've installed packetry, but I'm not able to record traffic due to the error message in the title of the issue. I noticed the docs have a section named 'Load Analyzer Bitstream', so I'm guessing I have to flash the analyzer bitstream onto the FPGA. Is there any documentation on how to do that?

In case it helps, I've installed all of this on a clean python venv and I'm on arch. My `cynthion info` is:

```
Detected a Cynthion device!
	Hardware: Cynthion r1.4
	Serial number: A5X33MKXXXXXX
	Firmware version: v1.0.3
	USB API version: 1.1
	Flash UID: 37648XXXXX
```

**Comment by martinling** [comment]
We're just working on a `cynthion` 1.0.0 release which will make this easier, but for now:

Since you've installed the latest from git, you should be able to build and load the analyzer bitstream with:

`python -m cynthion.gateware.analyzer.top --output analyzer.bit`

And then flash it to the board with:
`apollo flash-program analyzer.bit`

Then you'll have the latest gateware with the v1 protocol, which will work with the current Packetry from git.

**Comment by salcho** [comment]
Works great, thank you! Looking forward for 1.0.0
